=== brainiac/showeq/conf/seqpref.dtd
<!ENTITY % truthValues "(true | false | 1 | 0)">
<!ENTITY % simpleVariantTypes "(string | int | uint | double | bool | color | point | rect | size | key | font | sizepolicy | cursor | stringlist)">

<!ELEMENT seqpreferences (section*) >
<!ATTLIST seqpreferences 
 version CDATA #IMPLIED>

<!ELEMENT comment ANY>

<!ELEMENT section (property*) >
<!ATTLIST section name CDATA #REQUIRED>

<!ELEMENT property (comment*, %simpleVariantTypes;, comment*) >
<!ATTLIST property 
 name CDATA #REQUIRED>

<!ELEMENT string EMPTY>
<!ATTLIST string 
 value CDATA #REQUIRED
 encoding CDATA #IMPLIED>

<!ELEMENT int EMPTY>
<!ATTLIST int
 value CDATA #REQUIRED
 base CDATA "10">

<!ELEMENT uint EMPTY>
<!ATTLIST uint
 value CDATA #REQUIRED
 base CDATA "10">

<!ELEMENT double EMPTY>
<!ATTLIST double
 value CDATA #REQUIRED>

<!ELEMENT bool EMPTY>
<!ATTLIST bool
 value %truthValues; #REQUIRED>

<!ELEMENT color EMPTY>
<!ATTLIST color
 name CDATA #IMPLIED
 red CDATA #IMPLIED
 green CDATA #IMPLIED
 blue CDATA #IMPLIED
 base CDATA #IMPLIED>

<!ELEMENT point EMPTY>
<!ATTLIST point
 x CDATA "0"
 y CDATA "0"
 base CDATA "10">

<!ELEMENT rect EMPTY>
<!ATTLIST rect
 x CDATA "0"
 y CDATA "0"
 width CDATA "0"
 height CDATA "0"
 base CDATA "10">

<!ELEMENT size EMPTY>
<!ATTLIST size
 width CDATA "0"
 height CDATA "0"
 base CDATA "10">

<!ELEMENT key EMPTY>
<!ATTLIST key
 sequence CDATA #REQUIRED>

<!ELEMENT font EMPTY>
<!ATTLIST font
 family CDATA #IMPLIED
 pointsize CDATA #IMPLIED
 weight CDATA #IMPLIED
 italic %truthValues; #IMPLIED
 underline %truthValues; #IMPLIED
 strikeout %truthValues; #IMPLIED>

<!ELEMENT sizepolicy EMPTY>
<!ATTLIST sizepolicy
 hsizetype CDATA #IMPLIED
 vsizetype CDATA #IMPLIED
 horstretch CDATA #IMPLIED
 verstretch CDATA #IMPLIED>

<!ELEMENT cursor EMPTY>
<!ATTLIST cursor
 shape CDATA #REQUIRED>

<!ELEMENT stringlist (string*)>

<!--
<!ELEMENT list ((%simpleVariantTypes;)*)>

<!ELEMENT map ((string, %simpleVariantTypes;)*)>
-->

=== brainiac/showeq/conf/seqdef.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<!DOCTYPE seqpreferences SYSTEM "seqpref.dtd">
<!-- ============================================================= -->
<!-- NOTE: You'll save yourself a LOT of grief if you don't edit this 
     file, it should only need to be edited by developers and those
     that run multiple ShowEQ instances who are trying to maintain site 
     default preferences -->
<!-- ============================================================= -->
<seqpreferences version="1.0" >
<!-- ============================================================= -->
 <section name="Network" >
  <property name="Device" >
   <string value="eth0" />
   <comment>your network device</comment>
  </property>
  <property name="IP" >
   <string value="127.0.0.0" />
   <comment>IP of EQ Client, 127.0.0.0 is a wild card used to tell showeq to automatically grab the next eq session it finds</comment>
  </property>
  <property name="MAC" >
   <string value="" />
   <comment>MAC Address</comment>
  </property>
  <property name="RealTimeThread" >
   <bool value="false" />
   <comment>Put network in realtime thread</comment>
  </property>
  <property name="NoPromiscuous" >
   <bool value="true" />
   <comment>Don't use promiscous mode</comment>
  </property>
  <property name="ArqSeqGiveUp" >
   <int value="512" />
   <comment>Give up waiting for seq arq after cache fills to this size.  Don't set this too low, otherwise showeq will artificially skip packets, minimum is 32, modem users may want to set 512, dsl and cable users may choose 256 or less</comment>
  </property>
  <property name="SessionTracking" >
   <bool value="false" />
   <comment>enable/disable session tracking</comment>
  </property>
  <property name="WorldOPCodes" >
   <string value="worldopcodes.xml" />
   <comment>Name of the file containing data about world opcodes</comment>
  </property>
  <property name="ZoneOPCodes" >
   <string value="zoneopcodes.xml" />
   <comment>Name of the file containing data about zone opcodes</comment>
  </property>
 </section>
<!-- ============================================================= -->
 <section name="Defaults" >
  <property name="AutoDetectCharSettings" >
   <bool value="true" />
   <comment>Attempt to autodect level/race/class</comment>
  </property>
  <property name="DefaultLevel" >
   <int value="1" />
   <comment>Default level of your character</comment>
  </property>
  <property name="DefaultRace" >
   <int value="1" />
   <comment>Default race of your character = 1 HUM, 2 BAR, 3 ERU, 4 WLF, 5 HIE, 6 DELF, 7 HEF, 8 DWF, 9 TRL, 10 OGR, 11 HAF, 12 GNO, 128 IKS</comment>
  </property>
  <property name="DefaultClass" >
   <int value="1" />
   <comment>Default class for your character = 1 WAR, 2 CLE, 3 PAL, 4 RNG, 5 SHD, 6 DRU, 7 MNK, 8 BRD, 9 ROG, 10 SHM, 11 NEC, 12 WIZ, 13 MAG, 14 ENC</comment>
  </property>
  <property name="DefaultDeity" >
   <int value="140" />
   <comment>Default deity of your character = 140 Agn, 201 Bert, 202 Brell, 303 Cazic, 204 Erol, 205 Bristle, 206 Inny, 207 Karana, 208 Mith, 209 Prex, 210 Quell, 211 Rallows, 213 Solusek, 214 Tribunal, 215 Tun, 216 Rodcet, 216 Veeshan</comment>
  </property>
  <property name="DefaultName" >
   <string value="You" />
   <comment>Default name for your character</comment>
  </property>
  <property name="DefaultLastName" >
   <string value="" />
   <comment>Default last name of your character</comment>
  </property>
 </section>
<!-- ============================================================= -->
 <section name="Misc" >
  <property name="FastMachine" >
   <bool value="false" />
   <comment>set to true if you have a fast machine to enable more accurate calculations</comment>
  </property>
  <property name="CreateUnknownSpawns" >
   <bool value="true" />
   <comment>Create Unknown Spawns for those spawns with incomplete information</comment>
  </property>
  <property name="SpawnLogEnabled" >
   <bool value="false" />
   <comment>set to true to log spawns</comment>
  </property>
  <property name="SpawnLogFilename" >
   <string value="/usr/local/share/showeq/spawnlog.txt" />
   <comment>name of file to log spawns into</comment>
  </property>
  <property name="ShowSpellMessages" >
   <bool value="true" />
   <comment>Enable / disable spell casting messages</comment>
  </property>
  <property name="LogSpawns" >
   <bool value="false" />
   <comment>enable logging of spawns</comment>
  </property>
  <property name="LogItems" >
   <bool value="false" />
   <comment>enable logging of items</comment>
  </property>
  <property name="WalkPathRecording" >
   <bool value="false" />
   <comment>enable the recording of spawn walk paths</comment>
  </property>
  <property name="WalkPathLength" >
   <int value="25" />
   <comment>number of spawn walk points to save per spawn</comment>
  </property>
 </section>
<!-- ============================================================= -->
 <section name="VPacket" >
  <property name="Filename" >
   <string value="" />
   <comment>filename to play/record packets from/to</comment>
  </property>
  <property name="Record" >
   <bool value="false" />
   <comment>set to true to record packets from session to Filename</comment>
  </property>
  <property name="Playback" >
   <bool value="false" />
   <comment>set to true to playback packets from session in Filename</comment>
  </property>
  <property name="PlaybackRate" >
   <bool value="false" />
   <comment>Rate to playback; 0 = fast as possible, 1=1x, 2=2x, etc.</comment>
  </property>
  <property name="FlushPackets" >
   <bool value="true" />
   <comment>Flush recorded packets to disk after each packet (useful for diagnosing crash problems)</comment>
  </property>
  <property name="CompressTime" >
   <int value="0" />
   <comment>ignore timestamps (compress time) for pckts over 1 sec</comment>
  </property>
 </section>
<!-- ============================================================= -->
<!-- Skill List Options -->
 <section name="SkillList" >
  <property name="Caption" >
   <string value="ShowEQ - Skills" />
   <comment>Skill list window caption when undocked</comment>
  </property>
  <property name="Font" >
   <font family="adobe-helvetica" bold="false" strikeout="false" underline="false" pointsize="10" italic="false" />
  </property>
  <property name="SaveWidth" >
   <bool value="true" />
   <comment>Save column widths</comment>
  </property>
  <property name="ShowSkill" >
   <bool value="true" />
  </property>
  <property name="ShowValue" >
   <bool value="true" />
  </property>
  <property name="SkillWidth" >
   <int value="69" />
   <comment>pixel width of skill name column</comment>
  </property>
  <property name="ValueWidth" >
   <int value="30" />
   <comment>pixel width of skill value column</comment>
  </property>
  <property name="SaveShowLanguages" >
   <bool value="true" />
   <comment>Save show languages setting</comment>
  </property>
  <property name="ShowLanguages" >
   <bool value="true" />
   <comment>Skill list includes language skills</comment>
  </property>
  <property name="ColumnOrder" >
   <string value="0:1" />
   <comment>order of columns in skill list</comment>
  </property>
 </section>
<!-- ============================================================= -->
<!-- Stat List Options -->
 <section name="StatList" >
  <property name="Caption" >
   <string value="ShowEQ - Stats" />
   <comment>Window caption when undocked</comment>
  </property>
  <property name="Font" >
   <font family="adobe-helvetica" bold="false" strikeout="false" underline="false" pointsize="10" italic="false" />
  </property>
  <property name="ColumnOrder" >
   <string value="0:1:2:3" />
   <comment>order of columns in stat list display</comment>
  </property>
  <property name="ShowStat" >
   <bool value="true" />
  </property>
  <property name="ShowValue" >
   <bool value="true" />
  </property>
  <property name="ShowMax" >
   <bool value="true" />
  </property>
  <property name="ShowPercent" >
   <bool value="true" />
  </property>
  <property name="SaveWidth" >
   <bool value="true" />
   <comment>Save column widths</comment>
  </property>
  <property name="StatWidth" >
   <int value="35" />
   <comment>pixel width of stat name column</comment>
  </property>
  <property name="ValueWidth" >
   <int value="50" />
   <comment>pixel width of value column</comment>
  </property>
  <property name="MaxWidth" >
   <int value="50" />
   <comment>pixel width of max column</comment>
  </property>
  <property name="PercentWidth" >
   <int value="30" />
   <comment>pixel width of percent column</comment>
  </property>
  <property name="showStam" >
   <bool value="false" />
   <comment>Display Stamina</comment>
  </property>
  <property name="showMana" >
   <bool value="false" />
   <comment>Display Mana</comment>
  </property>
  <property name="showAC" >
   <bool value="false" />
   <comment>Display Armor Class</comment>
  </property>
  <property name="showExp" >
   <bool value="true" />
   <comment>Display Experience</comment>
  </property>
  <property name="showExpAA" >
   <bool value="true" />
   <comment>Display Alternative Advancement Experience</comment>
  </property>
  <property name="showDR" >
   <bool value="false" />
   <comment>Display Disease Resist</comment>
  </property>
  <property name="showHP" >
   <bool value="false" />
   <comment>Display Hit Points</comment>
  </property>
  <property name="showFR" >
   <bool value="false" />
   <comment>Display Fire Resist</comment>
  </property>
  <property name="showWatr" >
   <bool value="false" />
   <comment>Display Water value</comment>
  </property>
  <property name="showPR" >
   <bool value="false" />
   <comment>Display Poison Resist</comment>
  </property>
